spring.application.name=bdom-kikwit
#spring.h2.console.enabled=true
#spring.datasource.url=jdbc:h2:mem:bdom-db
spring.jackson.serialization.FAIL_ON_EMPTY_BEANS=false
server.port=8082

#spring.datasource.url=jdbc:postgresql://dpg-d87bkusm0tmc739o7ak0-a.oregon-postgres.render.com:5432/bdombd
#spring.datasource.username=bdombd_user
#spring.datasource.password=KtAm0fvZlk2VFM8U3GV3LKvpHk7Ibq7t

spring.datasource.url=jdbc:mysql://localhost:3306/bdom-db?serverTimezone=UTC&createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password= Fiston+@1984
#spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL5Dialect


spring.jpa.hibernate.ddl-auto= update
spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect


#Envoie mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=augumakuma@gmail.com
spring.mail.password= ufwbpibqtnswvxby

#spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=false
#spring.mail.properties.mail.smtp.starttls.enable=true


spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

#sendgrid.api.key=${SENDGRID_API_KEY}

