spring.application.name=bdom-kikwit
#spring.h2.console.enabled=true
#spring.datasource.url=jdbc:h2:mem:bdom-db
spring.jackson.serialization.FAIL_ON_EMPTY_BEANS=false
server.port=8081

spring.datasource.url=jdbc:postgresql://dpg-d87bkusm0tmc739o7ak0-a.oregon-postgres.render.com:5432/bdombd
spring.datasource.username=bdombd_user
spring.datasource.password=KtAm0fvZlk2VFM8U3GV3LKvpHk7Ibq7t

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect


#Envoie mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=augumakuma@gmail.com
spring.mail.password=ufwb pibq tnsw vxby

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

